"""Initial migration - create users table

Revision ID: a74dffe26155
Revises:
Create Date: 2025-12-17 10:21:41.812118

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a74dffe26155"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
