"""Change user id to UUID

Revision ID: fd09987c03eb
Revises: 93fb9dccfe23
Create Date: 2025-12-17 10:47:14.422881

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fd09987c03eb"
down_revision: Union[str, None] = "93fb9dccfe23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=mysql.INTEGER(),
        type_=mysql.CHAR(length=4),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.alter_column(
        "users",
        "id",
        existing_type=mysql.CHAR(length=4),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
