"""add firebase_id

Revision ID: 44172a7c3ca6
Revises: 680acd149615
Create Date: 2026-01-09 14:14:36.600686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "44172a7c3ca6"
down_revision: Union[str, None] = "680acd149615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("firebase_uid", sa.String(length=128), nullable=False)
    )
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.ENUM("ADMIN", "TENANT", "GUEST"),
        server_default="guest",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.ENUM("ADMIN", "TENANT", "GUEST"),
        server_default=sa.text("'GUEST'"),
        existing_nullable=False,
    )
    op.drop_column("users", "firebase_uid")
    # ### end Alembic commands ###
