"""remove firebase_id

Revision ID: 680acd149615
Revises: 3ab18aa455b7
Create Date: 2026-01-09 14:08:27.137292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '680acd149615'
down_revision: Union[str, None] = '3ab18aa455b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'TENANT', 'GUEST'),
               server_default='guest',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', mysql.VARCHAR(length=128), nullable=False))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'TENANT', 'GUEST'),
               server_default=sa.text("'GUEST'"),
               existing_nullable=False)
    # ### end Alembic commands ###
