"""add tenants and businesses

Revision ID: 9462b9567ea4
Revises: 9c5d0db4a7e5
Create Date: 2026-01-09 16:56:17.133114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9462b9567ea4"
down_revision: Union[str, None] = "9c5d0db4a7e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", mysql.CHAR(length=4), nullable=False),
        sa.Column("user_id", mysql.CHAR(length=4), nullable=False),
        sa.Column("nama_ketua_tim", sa.String(length=255), nullable=False),
        sa.Column("nim_nidn_ketua", sa.String(length=50), nullable=False),
        sa.Column("nama_anggota_tim", sa.String(length=255), nullable=True),
        sa.Column("nim_nidn_anggota", sa.String(length=50), nullable=True),
        sa.Column("nomor_telepon", sa.String(length=20), nullable=False),
        sa.Column("fakultas", sa.String(length=100), nullable=False),
        sa.Column("prodi", sa.String(length=100), nullable=False),
        sa.Column("nama_bisnis", sa.String(length=255), nullable=False),
        sa.Column("kategori_bisnis", sa.String(length=100), nullable=False),
        sa.Column("alamat_usaha", sa.Text(), nullable=False),
        sa.Column("jenis_usaha", sa.String(length=100), nullable=False),
        sa.Column("lama_usaha", sa.Integer(), nullable=False),
        sa.Column("omzet", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="tenantstatus"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_table(
        "business_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", mysql.CHAR(length=4), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("akun_medsos", sa.Text(), nullable=True),
        sa.Column("sertifikat_nib_url", sa.String(length=500), nullable=True),
        sa.Column("proposal_url", sa.String(length=500), nullable=True),
        sa.Column("bmc_url", sa.String(length=500), nullable=True),
        sa.Column("rab_url", sa.String(length=500), nullable=True),
        sa.Column("laporan_keuangan_url", sa.String(length=500), nullable=True),
        sa.Column("foto_produk_urls", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.ENUM("ADMIN", "TENANT", "GUEST"),
        server_default="guest",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.ENUM("ADMIN", "TENANT", "GUEST"),
        server_default=sa.text("'GUEST'"),
        existing_nullable=False,
    )
    op.drop_table("business_documents")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
